### ISSUE TITLE
Cover Image not Displayed on Kindle or Apple Books Shelf

### ISSUE THREAD

**Issue by nibl** [TekkCraft/epub-generator#1]
The EPUB files validate, but cover images are not displayed on the bookshelf in the Kindle app, Apple Books app, or the previews in file manager apps like the macOS Finder app or iOS Files app. They only display a generic cover image on the bookshelf.

To reproduce, open any EPUB file generated by this library in the Apple Books app or send to Kindle.

The issue is not related to side-loading because other EPUB files can be side-loaded and do show the cover image on the "shelves" of these apps, and also in file manager previews.

To be clear, the cover image is correctly displayed when the book is opened. Attached below are screenshots from Amazon Kindle and Apple Books displaying the book "shelves".

![IMG_2490](https://github.com/TekkCraft/epub-generator/assets/462866/b04713ed-1ce4-4a81-ae3c-6f11274ac652)

![IMG_2491](https://github.com/TekkCraft/epub-generator/assets/462866/16b48775-2c43-4517-a287-11f00adf13cf)

**Comment by TekkCraft** [comment]
@nibl This might be a problem with how these platforms handle epub uploads (see: https://www.reddit.com/r/kindle/comments/unlwhj/send_to_kindle_epub_doesnt_show_cover_art/).

I have tried this out using an example Ebook downloaded from Adobe (https://www.adobe.com/solutions/ebook/digital-editions/sample-ebook-library.html) and it also doesn't show the cover in the Kindle Library.

![image](https://github.com/TekkCraft/epub-generator/assets/21214298/d64758cd-82fc-4b38-b976-803cba502ffb)

The cover is displayed correctly when using other applications like [Icecream Ebook Reader](https://icecreamapps.com/Download-Ebook-Reader/):

![image](https://github.com/TekkCraft/epub-generator/assets/21214298/c1a5c83c-53da-49fc-85d6-91448a94a935)
